services:
  api:
    build:
      context: ../
    env_file:
      - .env
    ports:
      - ${API_PORT}:8080
    environment:
      - DB_PORT=${POSTGRES_PORT}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_USERNAME=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=${POSTGRES_HOST}
    restart: on-failure
    networks:
      - bdd
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14-alpine
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    networks:
      - bdd
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}

  pgadmin4:
    image: elestio/pgadmin:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${ADMIN_PASSWORD}
      - PGADMIN_LISTEN_PORT=8080
    ports:
      - "${PGADMIN_PORT}:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bdd

networks:
  bdd:
    driver: bridge
    external: false
  traefik:
    external: true