#--------Global configuration-------
spring:
  application:
    name: HoopHubApi
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jackson:
    serialization:
      write_dates_as_timestamps: false

  #--------JPA-ORM Properties-------
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: info