on:
  pull_request:
    branches: [ main, develop ]

jobs:
  check-branch-name:
    name: Check branch name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check branch name respects naming conventions
        id: branchnamecheck
        if: github.base_ref == 'main' || github.base_ref == 'develop'
        run: |
          echo "base ref is main or develop checking branch name..."
          ALLOWED_PREFIXES="feature feat fix hotfix release chore dependabot docs test refactor"
          BRANCH_NAME_VALID=false
          PREFIXES_ARRAY=$(echo $ALLOWED_PREFIXES | tr " " "\n")
          for PREFIX in $PREFIXES_ARRAY ; 
          do 
          if [[ "${{ github.head_ref }}" == $PREFIX/* ]]; then
              echo "${{ github.head_ref }} respects prefix $PREFIX"
              BRANCH_NAME_VALID=true
          else
              echo "${{ github.head_ref }} DOES NOT respects prefix $PREFIX"
          fi
          done
          if [[ $BRANCH_NAME_VALID == true ]]; then
              echo "[SUCCESS] - Your branch name respect the naming convention"  
          else
              echo "[FAIL] - Branch ${{ github.head_ref }} does not respect the naming convention, please rename"  
              exit 1
          fi
  check-commit-name:
    name: Check commit(s)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check commit name
        id: checkcommitname
        if: github.base_ref == 'main' || github.base_ref == 'develop'
        run: |
          echo "base ref is main or develop checking commit(s) name..."
          count=$(git rev-list --count origin/${{ github.base_ref }}..origin/${{ github.head_ref }})
          ALLOWED_PREFIXES="feat fix docs style refactor test chore"
          PREFIXES_ARRAY=$(echo $ALLOWED_PREFIXES | tr " " "\n")
          ALL_COMMIT_NAME_VALID=true
          if [ $count == 0 ]; then
            ALL_COMMIT_NAME_VALID=false
          else
            echo "Checking last commit"
            message=$(git log -1 --format=%s origin/${{ github.head_ref }})
            COMMIT_NAME_VALID=false
            for PREFIX in $PREFIXES_ARRAY ; 
            do 
            if [[ "$message" == $PREFIX\(*\):\ * ]]; then
                COMMIT_NAME_VALID=true
                echo "$message respects prefix $PREFIX"
            else
                echo "$message DOES NOT respects prefix $PREFIX"
            fi
            done
            if [[ $COMMIT_NAME_VALID == false ]]; then
                ALL_COMMIT_NAME_VALID=false
            fi
          fi
          if [[ $ALL_COMMIT_NAME_VALID == true ]]; then
              echo "[SUCCESS] - All your commit(s) respect the naming convention"  
          else
              echo "[FAIL] - At least one commit message does not respect the naming convention, please rename"  
              exit 1
          fi
  up-to-date:
    name: Check branch up to date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check up to date
        id: checkuptodate
        if: github.base_ref == 'main' || github.base_ref == 'develop'
        run: |
          echo "base ref is main or develop checking if branch is up to date..."
          count=$(git rev-list --count origin/${{ github.head_ref }}..origin/${{ github.base_ref }})
          if [ $count == 0 ]; then
            echo "[SUCCESS] - Your branch is up to date"  
          else
            echo "[FAIL] - your branch is $count commits late. Please rebase."  
            exit 1
          fi
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and Test with Maven
        env:
          SPRING_PROFILES_ACTIVE: test
        run: mvn clean install

  check-coverage:
    permissions: write-all
    name: Check code coverage
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Coverage
        env:
          SPRING_PROFILES_ACTIVE: test
        run: mvn clean verify

      - name: Upload Report
        uses: 'actions/upload-artifact@v4'
        with:
          name: report.xml
          path: ${{ github.workspace }}/target/site/jacoco/jacoco.xml

      - name: Jacoco Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 75
          debug-mode: false
          title: Code Coverage

      - name: Get the Coverage info
        run: |
          echo "coverage-overall=${{ steps.jacoco.outputs.coverage-overall }}" >> $GITHUB_ENV
          echo "coverage-changed-files=${{ steps.jacoco.outputs.coverage-changed-files }}" >> $GITHUB_ENV

      - name: Fail PR if overall coverage is less than 80%
        if: ${{ env.coverage-overall < 80.0 }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Overall coverage is less than 80%!')

name: Java CI with maven